services:
  - type: web
    name: tr-store-links
    runtime: node
    buildCommand: npm install --build-from-source
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
