services:
  - type: web
    name: tr-store-links
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
