services:
  - type: web
    name: tr-store-links
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
